#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and displays "Hi" at the 9th iteration

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
        ((counter++))
done
