#!/usr/bin/env bash
# This script is displaying "bad luck" for the 4th loop iteration, "good luck" for the 8th loop iteration,Best School for the other iterations

counter=1
while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
                        echo "bad luck from Japan"
                        ;;
		17)
			echo $counter
                        echo "bad luck from Italy"
                        ;;
		*)
			echo $counter
			;;
	esac
        ((counter++))
done

